[package]
name = "testing_project"
type = "bin"
authors = [""]

[dependencies]
CodeTracer = { git = "https://github.com/metacraft-labs/codetracer" }
rocq-of-noir = { git = "https://github.com/formal-land/rocq-of-noir" }
